spring.application.name=planetbooks-back
app.jwt.secret=estaselaclavenmassecretadelmundomundialdicenqueesmuycortaperono
app.jwt.expiration=3600000

# CORRECCIÓN: URL sin contraseña embebida
spring.datasource.url=jdbc:mysql://universaldb-8gpgd:3306/mysql?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=qdyxQzqH9S6I1mIAkDA

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Swagger / OpenAPI
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true